Repository FC-FastCatch/FastCatch-FrontEnd, pull requests merged in 2023-11, with the labels that each got.

#4 [#1] docs: 임시 목업 데이터 추가
  public/data/accommodationDetail.json
  public/data/cartData.json
  public/data/orderData.json
Labels: docs

#10 [#5] style: 글로벌 css 초기세팅 및 믹스인 설정
  .eslintrc.cjs
  index.html
  src/assets/fonts/PretendardVariable.woff2
  src/styles/_media-query.scss
  src/styles/_theme.scss
  src/styles/_typo.scss
  src/styles/_unit.scss
  src/styles/common.scss
  src/styles/reset.css
Labels: style

#11 [#2] design : 공통 컴포넌트 제작 ( 인풋, 버튼 )
  src/components/a.ts
  src/components/commonButton/CommonButton.tsx
  src/components/commonButton/commonButton.scss
  src/components/commonInput/CommonInput.tsx
  src/components/commonInput/commonInput.scss
  src/styles/_theme.scss
Labels: design

#20 [#17] design : 공통 컴포넌트 제작 ( 뱃지 )
  src/components/commonBadge/CommonBadge.tsx
  src/components/commonBadge/commonBadge.scss
  src/index.css
  src/main.tsx
  src/pages/basket/Basket.tsx
  src/pages/index.ts
Labels: design

#22 [#13] 공통 컴포넌트 모달 및 toast 모듈작업
  .prettierr.json
  package-lock.json
  package.json
  src/components/commonModal/CommonModalLayout.tsx
  src/components/commonModal/ModalPortal.tsx
  src/components/commonModal/commonModalLayout.scss
  src/components/commonToast/CommonToastLayout.tsx
  src/components/commonToast/commonToastLayout.scss
Labels: design

#24 [#12] 세부 상품 조회 페이지 초기 레이아웃 완성
  .prettierr.json
  package-lock.json
  package.json
  public/data/accommodationDetail.json
  src/components/Header/index.tsx
  src/pages/accommodation/accommodation.scss
  src/pages/accommodation/accommodation.tsx
  src/pages/accommodation/accommodationImgSwiper/AccommodationImgSwiper.tsx
  src/pages/accommodation/accommodationIntroduce/AccommodationIntroduce.tsx
  src/pages/accommodation/accommodationMainInfo/AccommodationMainInfo.tsx
  src/pages/accommodation/accommodationMainInfo/accommodationMainInfo.scss
  src/pages/accommodation/accommodationOptions/AccommodationOptions.tsx
  src/pages/accommodation/accommodationOptions/accommodationOptions.scss
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/accommodation/roomSelect/roomImgSwiper/RoomImgSwiper.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
  src/pages/accommodation/roomSelect/roomSelect.scss
  src/pages/order/Order.tsx
  src/utils/englishToKoreanFormat.ts
  src/utils/numberFormat.ts
  tsconfig.json
Labels: docs, feat, design, refactor

#26 [#3] Design: 장바구니 페이지 초기 레이아웃 및 컴포넌트화
  package-lock.json
  package.json
  src/components/index.ts
  src/components/selectedAccomodation/SelectedAccomodation.tsx
  src/components/selectedAccomodation/selectedAccomodation.scss
  src/components/selectedRoomItem/SelectedRoomItem.tsx
  src/components/selectedRoomItem/selectedRoomItem.scss
  src/pages/basket/Basket.tsx
  src/pages/basket/basket.scss
  src/pages/index.ts
  tsconfig.json
Labels: design

#27 [#09] 필터 컴포넌트 외형 퍼블리싱, 지역필터 모달 작업
  src/App.tsx
  src/components/CommonFilter/index.tsx
  src/components/Header/Header.scss
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonFilter/commonFilter.scss
  src/components/commonFilter/filterDropdowns/AmountDropdown.tsx
  src/components/commonFilter/filterDropdowns/DateDropdown.tsx
  src/components/commonFilter/filterDropdowns/LocationDropdown.tsx
  src/components/commonFilter/filterDropdowns/dropdown.scss
  src/components/commonFilter/filterDropdowns/locationDropdownEl/CurrentLocation.tsx
  src/components/commonFilter/filterDropdowns/locationDropdownEl/LocationCategoryName.tsx
  src/components/commonFilter/filterDropdowns/locationDropdownEl/LocationList.tsx
  src/components/commonFilter/filterDropdowns/locationDropdownEl/locationDropdownEls.scss
  src/components/commonHeader/CommonHeader.tsx
  src/components/commonHeader/commonHeader.scss
  src/components/commonHeader/myInfo/MyInfo.tsx
  src/components/commonHeader/myInfo/myInfo.scss
Labels: feat, design, style

#25 [#14] 로그인 회원가입 화면구현
  src/components/termsAgreementItem/TermsAgreementItem.tsx
  src/pages/index.ts
  src/pages/users/Users.tsx
  src/pages/users/login/Login.tsx
  src/pages/users/signup/Signup.tsx
  src/pages/users/users.scss
  src/routes/constants.ts
  src/routes/router.tsx
  src/styles/_media-query.scss
  src/styles/_unit.scss
  tsconfig.json
Labels: design

#29 [#23] 필수 체크 컴포넌트화, CommonButton 수정, 내 정보 수정 퍼블리싱, 절대경로
  src/App.tsx
  src/components/accommodationName/AccommodationName.tsx
  src/components/accommodationName/accommodationName.scss
  src/components/commonButton/CommonButton.tsx
  src/components/commonButton/commonButton.scss
  src/components/hotelName/HotelName.tsx
  src/components/selectedRoomItem/SelectedRoomItem.tsx
  src/components/termsAgreement/TermsAgreement.tsx
  src/context/TermsAgreementContext.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
  src/pages/index.ts
  src/pages/members/Members.tsx
  src/pages/members/members.scss
  src/pages/members/membersHeader/MembersHeader.tsx
  src/pages/members/membersHeader/membersHeader.scss
  src/pages/members/membersInfo/MembersInfo.tsx
  src/pages/members/membersInfo/membersInfo.scss
  src/pages/members/membersItem/MembersItem.tsx
  src/pages/members/membersItem/membersItem.scss
  src/pages/order/Order.tsx
  src/pages/order/bookerInformation/BookerInformation.tsx
  src/pages/order/orderItem/OrderItem.tsx
  src/pages/order/orderPrice/OrderPrice.tsx
  src/pages/order/orderTotalPrice/OrderTotalPrice.tsx
  src/pages/order/paymentMethod/PaymentMethod.tsx
  src/pages/order/paymentMethodItem/PaymentMethodItem.tsx
  src/pages/order/paymentMethodItem/paymentMethodItem.scss
  src/pages/orderList/OrderList.tsx
  src/pages/orderList/orderList.scss
  src/pages/orderList/orderListItem/OrderListItem.tsx
  src/pages/orderList/orderListItem/orderListItem.scss
  src/routes/constants.ts
  src/routes/router.tsx
Labels: feat, design, style

#35 [#28] 지역 모달 수정
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonFilter/filterDropdowns/LocationDropdown.tsx
  src/components/commonFilter/filterDropdowns/dropdown.scss
  src/components/commonFilter/filterDropdowns/locationDropdownEl/LocationCategoryName.tsx
  src/components/commonFilter/filterDropdowns/locationDropdownEl/LocationList.tsx
  src/components/commonFilter/filterDropdowns/locationDropdownEl/locationDropdownEls.scss
  src/components/commonHeader/CommonHeader.tsx
Labels: design, refactor

#36 [#32] feat : msw mocking 서버 연결하기
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browsers.ts
  src/mocks/dummy.json
  src/mocks/handlers.ts
  src/pages/accommodation/accommodation.tsx
  src/pages/accommodation/accommodationMainInfo/AccommodationMainInfo.tsx
  src/pages/accommodation/accommodationOptions/AccommodationOptions.tsx
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
Labels: feat

#38 [#33] body 태그에 먹힌 css 제거
  src/pages/users/Users.tsx
  src/pages/users/login/Login.tsx
  src/pages/users/signup/Signup.tsx
  src/pages/users/users.scss
Labels: fix

#37 [#31] 일정 모달(react-datePicker), 인원 모달 추가
  package-lock.json
  package.json
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonFilter/commonFilter.scss
  src/components/commonFilter/filterDropdowns/AmountDropdown.tsx
  src/components/commonFilter/filterDropdowns/DateDropdown.tsx
  src/components/commonFilter/filterDropdowns/dropdown.scss
  src/components/commonFilter/filterDropdowns/locationDropdownEl/CurrentLocation.tsx
  src/components/commonFilter/filterDropdowns/react-datepicker.scss
  src/components/commonHeader/CommonHeader.tsx
  src/components/commonHeader/commonHeader.scss
  src/pages/users/users.scss
Labels: feat, design

#41 [#39] 카테고리 필터 추가
  src/assets/categoryIcons/all.jpg
  src/assets/categoryIcons/guest-house.jpg
  src/assets/categoryIcons/hotel.jpg
  src/assets/categoryIcons/motel.jpg
  src/assets/categoryIcons/pension-fullvilla.jpg
  src/components/commonHeader/CommonHeader.tsx
  src/components/commonHeader/categoryFilter/CategoryFilter.tsx
  src/components/commonHeader/categoryFilter/DetailedCategoryModal.tsx
  src/components/commonHeader/categoryFilter/categoryFilter.scss
  src/components/commonHeader/commonHeader.scss
  src/routes/constants.ts
Labels: feat, design

#44 [#34] design: 메인페이지 숙소 아이템 레이아웃 작업
  src/pages/home/Home.tsx
  src/pages/home/accomodationItem/AccomodationItem.tsx
  src/pages/home/accomodationItem/accomodationItem.scss
  src/pages/home/home.scss
  src/pages/home/index.tsx
  src/pages/index.ts
Labels: design

#43 [#40] 장바구니 버튼과 검색 필터 추가
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonFilter/commonFilter.scss
  src/components/commonHeader/CommonHeader.tsx
  src/components/commonHeader/cartButton/CartButton.tsx
  src/components/commonHeader/cartButton/cartbutton.scss
  src/components/commonHeader/categoryFilter/CategoryFilter.tsx
  src/components/commonHeader/categoryFilter/categoryFilter.scss
  src/components/commonHeader/commonHeader.scss
  src/components/commonHeader/myInfo/MyInfo.tsx
  src/components/commonHeader/searchFilter/SearchFilter.tsx
  src/components/commonHeader/searchFilter/searchFilter.scss
  tsconfig.json
Labels: feat, design

#46 [#45] Feat : msw와 react-query를 이용한 데이터 get, post 작업
  package-lock.json
  package.json
  src/components/commonToast/CommonToastLayout.tsx
  src/main.tsx
  src/mocks/dummy.json
  src/mocks/handlers.ts
  src/pages/accommodation/Accommodation_.tsx
  src/pages/accommodation/accommodation.scss
  src/pages/accommodation/accommodation.tsx
  src/pages/accommodation/accommodationOptions/accommodationOptions.scss
  src/pages/accommodation/roomSelect/roomImgSwiper/RoomImgSwiper.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
  src/pages/index.ts
Labels: feat

#48 [#47] refactor: 전역 상태로 관리하던 isAllCheck 상태를 props로 내려주는 것으로 변경
  src/App.tsx
  src/components/termsAgreement/TermsAgreement.tsx
  src/context/TermsAgreementContext.tsx
  src/pages/order/Order.tsx
  src/pages/users/signup/Signup.tsx
Labels: refactor

#55 [#52] 메인페이지 msw 연결, react-query로 fetching 구현, constants에 카테고리영문<->한글 추가
  public/data/allAccommodations.json
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonFilter/commonFilter.scss
  src/components/commonFilter/filterDropdowns/AmountDropdown.tsx
  src/components/commonFilter/filterDropdowns/DateDropdown.tsx
  src/components/commonFilter/filterDropdowns/locationDropdownEl/LocationCategoryName.tsx
  src/constant/a.ts
  src/constant/categories.ts
  src/mocks/handlers.ts
  src/pages/home/Home.tsx
  src/pages/home/accomodationItem/AccomodationItem.tsx
  src/pages/home/accomodationItem/accomodationItem.scss
  src/pages/home/home.scss
  src/routes/constants.ts
  src/states/filterState.ts
  src/types/accommodations.ts
Labels: docs, feat

#60 [#56] 카테고리필터/디테일필터 작업 중간본(작업 도중 toss), 헤더의 모든 navigate버튼들 작동하게 하기
  src/components/commonHeader/cartButton/CartButton.tsx
  src/components/commonHeader/categoryFilter/CategoryFilter.tsx
  src/components/commonHeader/categoryFilter/DetailCategoryModal.tsx
  src/components/commonHeader/categoryFilter/DetailedCategoryModal.tsx
  src/components/commonHeader/categoryFilter/detailCategoryModal.scss
  src/components/commonHeader/myInfo/MyInfo.tsx
  src/components/commonModal/commonModalLayout.scss
Labels: feat, design

#58 [#51] Feat & Desgin : 지도API 연결 및 세부 디자인 수정 & API 연동완료
  index.html
  src/assets/icons/markerImg.svg
  src/components/commonFilter/commonFilter.scss
  src/components/commonToast/commonToastLayout.scss
  src/hooks/a.ts
  src/pages/accommodation/Accommodation.tsx
  src/pages/accommodation/accommodation.scss
  src/pages/accommodation/accommodationImgSwiper/AccommodationImgSwiper.tsx
  src/pages/accommodation/accommodationMainInfo/AccommodationMainInfo.tsx
  src/pages/accommodation/accommodationMap/AccommodationMap.tsx
  src/pages/accommodation/accommodationMap/accommodationMap.scss
  src/pages/accommodation/accommodationOptions/AccommodationOptions.tsx
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/accommodation/roomSelect/roomImgSwiper/RoomImgSwiper.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
  src/pages/accommodation/roomSelect/roomSelect.scss
  src/pages/index.ts
Labels: feat, design

#63 [#61] 서버 연동 거의 완료, commonFilter handler props 설정
  index.html
  src/api/api.ts
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonHeader/CommonHeader.tsx
  src/constant/categories.ts
  src/hooks/fetchAccommodations.ts
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/home/Home.tsx
  src/pages/home/accomodationItem/AccomodationItem.tsx
  src/pages/home/categoryFilter/CategoryFilter.tsx
  src/pages/home/categoryFilter/DetailCategoryModal.tsx
  src/pages/home/categoryFilter/categoryFilter.scss
  src/pages/home/categoryFilter/detailCategoryModal.scss
  src/pages/home/home.scss
  src/states/filterState.ts
  src/types/accommodations.ts
Labels: feat

#64 [#57] 예약자 이름, 휴대폰 번호 유효성 검사 및 axios instance , SelectedRoomItem 수정
  src/api/getOrderApi.ts
  src/api/instanceApi.ts
  src/components/commonButton/CommonButton.tsx
  src/components/commonButton/commonButton.scss
  src/components/commonInput/CommonInput.tsx
  src/constant/initialPaymentMethod.ts
  src/constant/validation.ts
  src/hooks/useValidation.tsx
  src/pages/order/Order.tsx
  src/pages/order/bookerInformation/BookerInformation.tsx
  src/pages/order/order.scss
  src/pages/order/paymentMethod/PaymentMethod.tsx
  src/pages/orderList/OrderList.tsx
  src/pages/orderList/orderList.scss
  src/pages/orderList/orderListItem/OrderListItem.tsx
  src/pages/orderList/orderRoomItem/OrderRoomItem.tsx
  src/pages/orderList/orderRoomItem/orderRoomItem.scss
  src/pages/users/signup/Signup.tsx
  src/states/orderState.ts
  src/types/order.ts
  src/types/roomInfo.ts
  src/utils/getDayOfWeek.ts
Labels: feat

#68 [#67] Feat : 주문하기 클릭 시 url 변경 및 전역 데이터 업데이트
  package-lock.json
  package.json
  src/pages/accommodation/Accommodation.tsx
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/accommodation/roomSelect/roomImgSwiper/RoomImgSwiper.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
Labels: feat

#71 [#62] 메인 디테일 모달 구현
  src/hooks/apiHook.ts
  src/pages/home/categoryFilter/CategoryFilter.tsx
  src/pages/home/categoryFilter/DetailCategoryModal.tsx
  src/pages/home/categoryFilter/detailCategoryModal.scss
  src/pages/home/detailFilter/DetailCategoryModal.tsx
  src/pages/home/detailFilter/detailCategoryModal.scss
  src/pages/home/detailFilter/detailCommitFnc.ts
  src/pages/index.ts
  src/pages/users/login/Login.tsx
  src/pages/users/signup/Signup.tsx
  src/states/detailState.ts
Labels: feat

#73 [#63] 메인페이지 AccommodationItem 이미지 & 주소 연결, 카테고리 선택 시에도 서버 호출, 인피니티 스크롤 구현, 필터 버그 수정, 카테고리 전환 시 '없어요' 버그 수정
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonFilter/commonFilter.scss
  src/components/commonHeader/CommonHeader.tsx
  src/components/commonHeader/categoryFilter/CategoryFilter.tsx
  src/components/commonHeader/categoryFilter/categoryFilter.scss
  src/hooks/fetchAccommodations.ts
  src/pages/home/Home.tsx
  src/pages/home/accomodationItem/AccomodationItem.tsx
  src/pages/home/accomodationItem/accomodationItem.scss
  src/pages/home/home.scss
  src/states/filterState.ts
  src/states/responseState.ts
  src/types/accommodations.ts
Labels: fix, feat, refactor

#77 [#73] 주소 연결, 디테일 모달 연결, 디테일 모달 취소 로직 구현, 메인페이지 아이템 이름/주소 너무 길 시 말줄임 표시
  src/components/commonFilter/CommonFilter.tsx
  src/components/commonHeader/categoryFilter/CategoryFilter.tsx
  src/constant/categories.ts
  src/pages/home/Home.tsx
  src/pages/home/accomodationItem/AccomodationItem.tsx
  src/pages/home/accomodationItem/accomodationItem.scss
  src/pages/home/detailFilter/DetailCategoryModal.tsx
  src/pages/home/detailFilter/detailCategoryModal.scss
  src/pages/home/detailFilter/detailCommitFnc.ts
  src/pages/home/home.scss
  src/types/accommodations.ts
Labels: feat, design

#80 [#79] Feat : 지도 내 편의시설 검색 기능 추가
  index.html
  src/pages/accommodation/Accommodation.tsx
  src/pages/accommodation/accommodationMainInfo/AccommodationMainInfo.tsx
  src/pages/accommodation/accommodationMainInfo/accommodationMainInfo.scss
  src/pages/accommodation/accommodationMap/AccommodationMap.tsx
  src/pages/accommodation/accommodationMap/accommodationMap.scss
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/accommodation/roomSelect/roomImgSwiper/RoomImgSwiper.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
  src/pages/accommodation/roomSelect/roomSelect.scss
Labels: feat

#88 [#87] Fix : 상세 페이지에서 즉시 결제하기 버튼 비로그인시 로그인 페이지로 이동
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
Labels: fix

#81 [#78] 검색기능 구현, 검색 에러처리, 로그아웃 버튼 구현
  src/components/commonHeader/CommonHeader.tsx
  src/components/commonHeader/cartButton/CartButton.tsx
  src/components/commonHeader/logoutButton/LogoutButton.tsx
  src/components/commonHeader/myInfo/myInfo.scss
  src/components/commonHeader/searchFilter/SearchFilter.tsx
  src/components/commonModal/CommonModalLayout.tsx
  src/components/commonModal/commonModalLayout.scss
  src/hooks/fetchAccommodations.ts
  src/pages/home/Home.tsx
Labels: feat

#86 [#85] 헤더 카트버튼, 이미지 버튼 보이기
  src/components/commonHeader/cartButton/CartButton.tsx
  src/components/commonHeader/cartButton/cartbutton.scss
  src/components/commonHeader/myInfo/MyInfo.tsx
  src/components/commonHeader/myInfo/myInfo.scss
  src/pages/users/signup/Signup.tsx
Labels: feat, design

#94 [#66] feat: 장바구니 결제 오류 수정
  src/api/postOrderApi.ts
  src/pages/order/Order.tsx
  src/pages/order/orderItem/OrderItem.tsx
  src/states/orderState.ts
Labels: fix
