Repository FC-FastCatch/FastCatch-FrontEnd, pull requests merged in 2023-12, with the labels that each got.

#105 [#103] setTimeout 제거, 로티 애니메이션 추가, 변경된 api키 교체
  package-lock.json
  package.json
  src/components/common/header/Header.tsx
  src/components/common/header/cartButton/CartButton.tsx
  src/components/common/header/categoryFilter/CategoryFilter.tsx
  src/components/errorAnimation/ErrorAnimation.tsx
  src/components/loadingAnimation/LoadingAnimation.tsx
  src/hooks/fetchAccommodations.ts
  src/main.tsx
  src/pages/home/Home.tsx
  src/pages/home/home.scss
  vite.config.ts
Labels: fix, feat, design

#108 [#106] 로그인페이지 배경화면 추가 및 반응형 작업
  src/assets/images/login-bg.jpg
  src/components/common/button/button.scss
  src/components/termsAgreement/termsAgreement.scss
  src/components/termsAgreementItem/termsAgreementItem.scss
  src/pages/home/detailFilter/detailCommitFnc.ts
  src/pages/users/login/Login.tsx
  src/pages/users/signup/Signup.tsx
  src/pages/users/users.scss
  src/styles/_typo.scss
Labels: design

#111 [#103] 필터 버그 수정 및 필터링 시 선택 카테고리만 담게 설정
  src/pages/home/detailFilter/DetailCategoryModal.tsx
  src/pages/home/detailFilter/detailCommitFnc.ts
Labels: fix

#113 [#99] 구매 페이지 리팩토링
  src/components/termsAgreement/TermsAgreement.tsx
  src/components/termsAgreementItem/TermsAgreementItem.tsx
  src/pages/order/Order.tsx
  src/pages/order/bookerInformation/BookerInformation.tsx
  src/pages/order/eventBanner/EventBanner.tsx
  src/pages/order/orderItem/OrderItem.tsx
  src/pages/order/orderTotalPrice/OrderTotalPrice.tsx
  src/pages/order/paymentMethod/PaymentMethod.tsx
  src/pages/order/paymentMethodItem/PaymentMethodItem.tsx
Labels: refactor

#115 [#114] 주문 목록 페이지 리팩토링
  src/api/deleteOrderApi.ts
  src/api/getOrderApi.ts
  src/api/getOrderListApi.ts
  src/api/getUserInfoApi.ts
  src/api/instanceApi.ts
  src/api/postOrderApi.ts
  src/api/putUserInfoApi.ts
  src/components/errorAnimation/ErrorAnimation.scss
  src/components/errorAnimation/ErrorAnimation.tsx
  src/components/loadingAnimation/LoadingAnimation.scss
  src/components/loadingAnimation/LoadingAnimation.tsx
  src/pages/members/membersHeader/MembersHeader.tsx
  src/pages/members/membersInfo/MembersInfo.tsx
  src/pages/order/Order.tsx
  src/pages/order/bookerInformation/BookerInformation.tsx
  src/pages/orderList/OrderList.tsx
  src/pages/orderList/orderListItem/OrderListItem.tsx
Labels: feat, refactor

#118 [#112] 로그아웃, 재발급 토큰 서버연결
  src/api/instanceApi.ts
  src/api/refreshApi.ts
  src/components/common/header/logoutButton/LogoutButton.tsx
  src/hooks/useAuth.tsx
  src/main.tsx
  src/pages/orderList/orderListItem/orderListItem.scss
  src/pages/users/login/Login.tsx
  src/pages/users/signup/Signup.tsx
  src/types/member.ts
  src/utils/checkToken.ts
  src/utils/getToken.ts
Labels: feat

#120 [#119] Refactor : 폰트 성능 최적화
  index.html
  src/styles/reset.css
Labels: refactor

#123 [#122] responseStates 타입 수정
  src/pages/home/detailFilter/DetailCategoryModal.tsx
Labels: fix

#121 [#101] Refactor : API 요청 react-query로 수정
  src/pages/basket/Basket.tsx
  src/pages/basket/selectedAccomodation/SelectedAccomodation.tsx
  src/pages/basket/selectedRoomItem/SelectedRoomItem.tsx
  src/utils/calculateTotalRoomsAndPrice.ts
Labels: refactor

#126 [#125] useMemo 삭제 및 리드미 수정
  README.md
  src/pages/accommodation/Accommodation.tsx
  src/pages/accommodation/roomSelect/RoomSelect.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
Labels: docs, refactor

#136 [#135] 숙소 상세 페이지 반응형 디자인
  README.md
  src/pages/accommodation/Accommodation.tsx
  src/pages/accommodation/accommodation.scss
  src/pages/accommodation/roomSelect/roomImgSwiper/RoomImgSwiper.tsx
  src/pages/accommodation/roomSelect/roomInfo/RoomInfo.tsx
  src/pages/accommodation/roomSelect/roomSelect.scss
Labels: design

#138 [#137] token 저장 위치 변경
  package-lock.json
  package.json
  src/api/instanceApi.ts
  src/components/common/header/logoutButton/LogoutButton.tsx
  src/components/common/header/myInfo/MyInfo.tsx
  src/hooks/useAuth.tsx
  src/pages/home/Home.tsx
  src/utils/getToken.ts
Labels: refactor
